import React, {useState} from "react";
import Button from 'react-bootstrap/Button';
import Card from "./Card";
import axios from 'axios';
import { useRef } from 'react';
// remove once API call is working...


function Header(){
    const mockData = {
        "location": {
          "name": "Cocoa",
          "region": "Florida",
          "country": "USA",
          "lat": 28.39,
          "lon": -80.79,
          "tz_id": "America/New_York",
          "localtime_epoch": 1678835366,
          "localtime": "2023-03-14 19:09"
        },
        "current": {
          "last_updated_epoch": 1678834800,
          "last_updated": "2023-03-14 19:00",
          "temp_c": 21,
          "temp_f": 69.8,
          "is_day": 1,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "wind_mph": 11.9,
          "wind_kph": 19.1,
          "wind_degree": 40,
          "wind_dir": "NE",
          "pressure_mb": 1018,
          "pressure_in": 30.06,
          "precip_mm": 0,
          "precip_in": 0,
          "humidity": 46,
          "cloud": 0,
          "feelslike_c": 21,
          "feelslike_f": 69.8,
          "vis_km": 11,
          "vis_miles": 6,
          "uv": 6,
          "gust_mph": 13.6,
          "gust_kph": 22
        },
        "forecast": {
          "forecastday": [
            {
              "date": "2023-03-14",
              "date_epoch": 1678752000,
              "day": {
                "maxtemp_c": 23.5,
                "maxtemp_f": 74.3,
                "mintemp_c": 15.7,
                "mintemp_f": 60.3,
                "avgtemp_c": 18.9,
                "avgtemp_f": 66,
                "maxwind_mph": 12.8,
                "maxwind_kph": 20.5,
                "totalprecip_mm": 0,
                "totalprecip_in": 0,
                "totalsnow_cm": 0,
                "avgvis_km": 9.9,
                "avgvis_miles": 6,
                "avghumidity": 67,
                "daily_will_it_rain": 0,
                "daily_chance_of_rain": 0,
                "daily_will_it_snow": 0,
                "daily_chance_of_snow": 0,
                "condition": {
                  "text": "Sunny",
                  "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  "code": 1000
                },
                "uv": 5
              },
              "astro": {
                "sunrise": "07:34 AM",
                "sunset": "07:31 PM",
                "moonrise": "01:39 AM",
                "moonset": "12:00 PM",
                "moon_phase": "Waning Gibbous",
                "moon_illumination": "62",
                "is_moon_up": 0,
                "is_sun_up": 0
              },
              "hour": [
                {
                  "time_epoch": 1678766400,
                  "time": "2023-03-14 00:00",
                  "temp_c": 19.8,
                  "temp_f": 67.6,
                  "is_day": 0,
                  "condition": {
                    "text": "Partly cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                  },
                  "wind_mph": 5.1,
                  "wind_kph": 8.3,
                  "wind_degree": 346,
                  "wind_dir": "NNW",
                  "pressure_mb": 1015,
                  "pressure_in": 29.96,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 83,
                  "cloud": 60,
                  "feelslike_c": 19.8,
                  "feelslike_f": 67.6,
                  "windchill_c": 19.8,
                  "windchill_f": 67.6,
                  "heatindex_c": 19.8,
                  "heatindex_f": 67.6,
                  "dewpoint_c": 16.9,
                  "dewpoint_f": 62.4,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 9,
                  "vis_miles": 5,
                  "gust_mph": 8.5,
                  "gust_kph": 13.7,
                  "uv": 1
                },
                {
                  "time_epoch": 1678770000,
                  "time": "2023-03-14 01:00",
                  "temp_c": 19,
                  "temp_f": 66.2,
                  "is_day": 0,
                  "condition": {
                    "text": "Partly cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                  },
                  "wind_mph": 6,
                  "wind_kph": 9.7,
                  "wind_degree": 331,
                  "wind_dir": "NNW",
                  "pressure_mb": 1015,
                  "pressure_in": 29.97,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 85,
                  "cloud": 38,
                  "feelslike_c": 19,
                  "feelslike_f": 66.2,
                  "windchill_c": 19,
                  "windchill_f": 66.2,
                  "heatindex_c": 19,
                  "heatindex_f": 66.2,
                  "dewpoint_c": 16.4,
                  "dewpoint_f": 61.5,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.5,
                  "gust_kph": 16.9,
                  "uv": 1
                },
                {
                  "time_epoch": 1678773600,
                  "time": "2023-03-14 02:00",
                  "temp_c": 18.3,
                  "temp_f": 64.9,
                  "is_day": 0,
                  "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                  },
                  "wind_mph": 7.2,
                  "wind_kph": 11.5,
                  "wind_degree": 326,
                  "wind_dir": "NNW",
                  "pressure_mb": 1015,
                  "pressure_in": 29.98,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 84,
                  "cloud": 7,
                  "feelslike_c": 18.3,
                  "feelslike_f": 64.9,
                  "windchill_c": 18.3,
                  "windchill_f": 64.9,
                  "heatindex_c": 18.3,
                  "heatindex_f": 64.9,
                  "dewpoint_c": 15.6,
                  "dewpoint_f": 60.1,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 9,
                  "vis_miles": 5,
                  "gust_mph": 12.3,
                  "gust_kph": 19.8,
                  "uv": 1
                },
                {
                  "time_epoch": 1678777200,
                  "time": "2023-03-14 03:00",
                  "temp_c": 17.6,
                  "temp_f": 63.7,
                  "is_day": 0,
                  "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                  },
                  "wind_mph": 7.6,
                  "wind_kph": 12.2,
                  "wind_degree": 336,
                  "wind_dir": "NNW",
                  "pressure_mb": 1015,
                  "pressure_in": 29.98,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 85,
                  "cloud": 1,
                  "feelslike_c": 17.6,
                  "feelslike_f": 63.7,
                  "windchill_c": 17.6,
                  "windchill_f": 63.7,
                  "heatindex_c": 17.6,
                  "heatindex_f": 63.7,
                  "dewpoint_c": 15.1,
                  "dewpoint_f": 59.2,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 12.8,
                  "gust_kph": 20.5,
                  "uv": 1
                },
                {
                  "time_epoch": 1678780800,
                  "time": "2023-03-14 04:00",
                  "temp_c": 17.3,
                  "temp_f": 63.1,
                  "is_day": 0,
                  "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                  },
                  "wind_mph": 8.1,
                  "wind_kph": 13,
                  "wind_degree": 338,
                  "wind_dir": "NNW",
                  "pressure_mb": 1016,
                  "pressure_in": 29.99,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 86,
                  "cloud": 23,
                  "feelslike_c": 17.3,
                  "feelslike_f": 63.1,
                  "windchill_c": 17.3,
                  "windchill_f": 63.1,
                  "heatindex_c": 17.3,
                  "heatindex_f": 63.1,
                  "dewpoint_c": 14.8,
                  "dewpoint_f": 58.6,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 14.5,
                  "gust_kph": 23.4,
                  "uv": 1
                },
                {
                  "time_epoch": 1678784400,
                  "time": "2023-03-14 05:00",
                  "temp_c": 17.6,
                  "temp_f": 63.7,
                  "is_day": 0,
                  "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                  },
                  "wind_mph": 7.4,
                  "wind_kph": 11.9,
                  "wind_degree": 319,
                  "wind_dir": "NW",
                  "pressure_mb": 1015,
                  "pressure_in": 29.97,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 82,
                  "cloud": 8,
                  "feelslike_c": 17.6,
                  "feelslike_f": 63.7,
                  "windchill_c": 17.6,
                  "windchill_f": 63.7,
                  "heatindex_c": 17.6,
                  "heatindex_f": 63.7,
                  "dewpoint_c": 14.4,
                  "dewpoint_f": 57.9,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 13.6,
                  "gust_kph": 22,
                  "uv": 1
                },
                {
                  "time_epoch": 1678788000,
                  "time": "2023-03-14 06:00",
                  "temp_c": 16.8,
                  "temp_f": 62.2,
                  "is_day": 0,
                  "condition": {
                    "text": "Cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                    "code": 1006
                  },
                  "wind_mph": 6.9,
                  "wind_kph": 11.2,
                  "wind_degree": 335,
                  "wind_dir": "NNW",
                  "pressure_mb": 1016,
                  "pressure_in": 29.99,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 83,
                  "cloud": 66,
                  "feelslike_c": 16.8,
                  "feelslike_f": 62.2,
                  "windchill_c": 16.8,
                  "windchill_f": 62.2,
                  "heatindex_c": 16.8,
                  "heatindex_f": 62.2,
                  "dewpoint_c": 13.8,
                  "dewpoint_f": 56.8,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 13.6,
                  "gust_kph": 22,
                  "uv": 1
                },
                {
                  "time_epoch": 1678791600,
                  "time": "2023-03-14 07:00",
                  "temp_c": 16.4,
                  "temp_f": 61.5,
                  "is_day": 0,
                  "condition": {
                    "text": "Partly cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                  },
                  "wind_mph": 7.2,
                  "wind_kph": 11.5,
                  "wind_degree": 335,
                  "wind_dir": "NNW",
                  "pressure_mb": 1017,
                  "pressure_in": 30.02,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 82,
                  "cloud": 47,
                  "feelslike_c": 16.4,
                  "feelslike_f": 61.5,
                  "windchill_c": 16.4,
                  "windchill_f": 61.5,
                  "heatindex_c": 16.4,
                  "heatindex_f": 61.5,
                  "dewpoint_c": 13.4,
                  "dewpoint_f": 56.1,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 13.9,
                  "gust_kph": 22.3,
                  "uv": 1
                },
                {
                  "time_epoch": 1678795200,
                  "time": "2023-03-14 08:00",
                  "temp_c": 15.7,
                  "temp_f": 60.3,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 6.7,
                  "wind_kph": 10.8,
                  "wind_degree": 322,
                  "wind_dir": "NW",
                  "pressure_mb": 1017,
                  "pressure_in": 30.04,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 85,
                  "cloud": 8,
                  "feelslike_c": 15.7,
                  "feelslike_f": 60.3,
                  "windchill_c": 15.7,
                  "windchill_f": 60.3,
                  "heatindex_c": 15.7,
                  "heatindex_f": 60.3,
                  "dewpoint_c": 13.1,
                  "dewpoint_f": 55.6,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 13.4,
                  "gust_kph": 21.6,
                  "uv": 5
                },
                {
                  "time_epoch": 1678798800,
                  "time": "2023-03-14 09:00",
                  "temp_c": 16.7,
                  "temp_f": 62.1,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 9.4,
                  "wind_kph": 15.1,
                  "wind_degree": 333,
                  "wind_dir": "NNW",
                  "pressure_mb": 1018,
                  "pressure_in": 30.07,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 77,
                  "cloud": 0,
                  "feelslike_c": 16.7,
                  "feelslike_f": 62.1,
                  "windchill_c": 16.7,
                  "windchill_f": 62.1,
                  "heatindex_c": 16.7,
                  "heatindex_f": 62.1,
                  "dewpoint_c": 12.7,
                  "dewpoint_f": 54.9,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 13.9,
                  "gust_kph": 22.3,
                  "uv": 5
                },
                {
                  "time_epoch": 1678802400,
                  "time": "2023-03-14 10:00",
                  "temp_c": 18.5,
                  "temp_f": 65.3,
                  "is_day": 1,
                  "condition": {
                    "text": "Partly cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    "code": 1003
                  },
                  "wind_mph": 10.1,
                  "wind_kph": 16.2,
                  "wind_degree": 347,
                  "wind_dir": "NNW",
                  "pressure_mb": 1019,
                  "pressure_in": 30.08,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 65,
                  "cloud": 29,
                  "feelslike_c": 18.5,
                  "feelslike_f": 65.3,
                  "windchill_c": 18.5,
                  "windchill_f": 65.3,
                  "heatindex_c": 18.5,
                  "heatindex_f": 65.3,
                  "dewpoint_c": 11.8,
                  "dewpoint_f": 53.2,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 11.9,
                  "gust_kph": 19.1,
                  "uv": 5
                },
                {
                  "time_epoch": 1678806000,
                  "time": "2023-03-14 11:00",
                  "temp_c": 19.2,
                  "temp_f": 66.6,
                  "is_day": 1,
                  "condition": {
                    "text": "Partly cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    "code": 1003
                  },
                  "wind_mph": 8.7,
                  "wind_kph": 14,
                  "wind_degree": 359,
                  "wind_dir": "N",
                  "pressure_mb": 1019,
                  "pressure_in": 30.09,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 59,
                  "cloud": 54,
                  "feelslike_c": 19.2,
                  "feelslike_f": 66.6,
                  "windchill_c": 19.2,
                  "windchill_f": 66.6,
                  "heatindex_c": 19.2,
                  "heatindex_f": 66.6,
                  "dewpoint_c": 11,
                  "dewpoint_f": 51.8,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.1,
                  "gust_kph": 16.2,
                  "uv": 5
                },
                {
                  "time_epoch": 1678809600,
                  "time": "2023-03-14 12:00",
                  "temp_c": 20,
                  "temp_f": 68,
                  "is_day": 1,
                  "condition": {
                    "text": "Partly cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    "code": 1003
                  },
                  "wind_mph": 8.7,
                  "wind_kph": 14,
                  "wind_degree": 1,
                  "wind_dir": "N",
                  "pressure_mb": 1019,
                  "pressure_in": 30.1,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 55,
                  "cloud": 44,
                  "feelslike_c": 20,
                  "feelslike_f": 68,
                  "windchill_c": 20,
                  "windchill_f": 68,
                  "heatindex_c": 20,
                  "heatindex_f": 68,
                  "dewpoint_c": 10.8,
                  "dewpoint_f": 51.4,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.1,
                  "gust_kph": 16.2,
                  "uv": 6
                },
                {
                  "time_epoch": 1678813200,
                  "time": "2023-03-14 13:00",
                  "temp_c": 20.2,
                  "temp_f": 68.4,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 9.4,
                  "wind_kph": 15.1,
                  "wind_degree": 11,
                  "wind_dir": "NNE",
                  "pressure_mb": 1019,
                  "pressure_in": 30.09,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 56,
                  "cloud": 9,
                  "feelslike_c": 20.2,
                  "feelslike_f": 68.4,
                  "windchill_c": 20.2,
                  "windchill_f": 68.4,
                  "heatindex_c": 20.2,
                  "heatindex_f": 68.4,
                  "dewpoint_c": 11,
                  "dewpoint_f": 51.8,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.7,
                  "gust_kph": 17.3,
                  "uv": 6
                },
                {
                  "time_epoch": 1678816800,
                  "time": "2023-03-14 14:00",
                  "temp_c": 21.5,
                  "temp_f": 70.7,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 9.2,
                  "wind_kph": 14.8,
                  "wind_degree": 15,
                  "wind_dir": "NNE",
                  "pressure_mb": 1019,
                  "pressure_in": 30.09,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 52,
                  "cloud": 4,
                  "feelslike_c": 21.5,
                  "feelslike_f": 70.7,
                  "windchill_c": 21.5,
                  "windchill_f": 70.7,
                  "heatindex_c": 24.4,
                  "heatindex_f": 75.9,
                  "dewpoint_c": 11.3,
                  "dewpoint_f": 52.3,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.5,
                  "gust_kph": 16.9,
                  "uv": 6
                },
                {
                  "time_epoch": 1678820400,
                  "time": "2023-03-14 15:00",
                  "temp_c": 21.3,
                  "temp_f": 70.3,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 9.2,
                  "wind_kph": 14.8,
                  "wind_degree": 19,
                  "wind_dir": "NNE",
                  "pressure_mb": 1019,
                  "pressure_in": 30.08,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 50,
                  "cloud": 15,
                  "feelslike_c": 21.3,
                  "feelslike_f": 70.3,
                  "windchill_c": 21.3,
                  "windchill_f": 70.3,
                  "heatindex_c": 24.3,
                  "heatindex_f": 75.7,
                  "dewpoint_c": 10.4,
                  "dewpoint_f": 50.7,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.5,
                  "gust_kph": 16.9,
                  "uv": 6
                },
                {
                  "time_epoch": 1678824000,
                  "time": "2023-03-14 16:00",
                  "temp_c": 23.5,
                  "temp_f": 74.3,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 9.4,
                  "wind_kph": 15.1,
                  "wind_degree": 22,
                  "wind_dir": "NNE",
                  "pressure_mb": 1018,
                  "pressure_in": 30.07,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 48,
                  "cloud": 0,
                  "feelslike_c": 24.9,
                  "feelslike_f": 76.8,
                  "windchill_c": 23.5,
                  "windchill_f": 74.3,
                  "heatindex_c": 24.9,
                  "heatindex_f": 76.8,
                  "dewpoint_c": 11.9,
                  "dewpoint_f": 53.4,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.7,
                  "gust_kph": 17.3,
                  "uv": 6
                },
                {
                  "time_epoch": 1678827600,
                  "time": "2023-03-14 17:00",
                  "temp_c": 23.4,
                  "temp_f": 74.1,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 10.5,
                  "wind_kph": 16.9,
                  "wind_degree": 32,
                  "wind_dir": "NNE",
                  "pressure_mb": 1018,
                  "pressure_in": 30.07,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 48,
                  "cloud": 0,
                  "feelslike_c": 24.8,
                  "feelslike_f": 76.6,
                  "windchill_c": 23.4,
                  "windchill_f": 74.1,
                  "heatindex_c": 24.8,
                  "heatindex_f": 76.6,
                  "dewpoint_c": 11.7,
                  "dewpoint_f": 53.1,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 12.1,
                  "gust_kph": 19.4,
                  "uv": 6
                },
                {
                  "time_epoch": 1678831200,
                  "time": "2023-03-14 18:00",
                  "temp_c": 22.7,
                  "temp_f": 72.9,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 12.8,
                  "wind_kph": 20.5,
                  "wind_degree": 33,
                  "wind_dir": "NNE",
                  "pressure_mb": 1019,
                  "pressure_in": 30.08,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 50,
                  "cloud": 0,
                  "feelslike_c": 24.6,
                  "feelslike_f": 76.3,
                  "windchill_c": 22.7,
                  "windchill_f": 72.9,
                  "heatindex_c": 24.6,
                  "heatindex_f": 76.3,
                  "dewpoint_c": 11.6,
                  "dewpoint_f": 52.9,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 14.8,
                  "gust_kph": 23.8,
                  "uv": 6
                },
                {
                  "time_epoch": 1678834800,
                  "time": "2023-03-14 19:00",
                  "temp_c": 20.6,
                  "temp_f": 69.1,
                  "is_day": 1,
                  "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                  },
                  "wind_mph": 11,
                  "wind_kph": 17.6,
                  "wind_degree": 28,
                  "wind_dir": "NNE",
                  "pressure_mb": 1019,
                  "pressure_in": 30.1,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 53,
                  "cloud": 3,
                  "feelslike_c": 20.6,
                  "feelslike_f": 69.1,
                  "windchill_c": 20.6,
                  "windchill_f": 69.1,
                  "heatindex_c": 20.6,
                  "heatindex_f": 69.1,
                  "dewpoint_c": 10.8,
                  "dewpoint_f": 51.4,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 13.6,
                  "gust_kph": 22,
                  "uv": 6
                },
                {
                  "time_epoch": 1678838400,
                  "time": "2023-03-14 20:00",
                  "temp_c": 17.4,
                  "temp_f": 63.3,
                  "is_day": 0,
                  "condition": {
                    "text": "Partly cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                  },
                  "wind_mph": 9.2,
                  "wind_kph": 14.8,
                  "wind_degree": 27,
                  "wind_dir": "NNE",
                  "pressure_mb": 1019,
                  "pressure_in": 30.1,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 59,
                  "cloud": 34,
                  "feelslike_c": 17.4,
                  "feelslike_f": 63.3,
                  "windchill_c": 17.4,
                  "windchill_f": 63.3,
                  "heatindex_c": 17.4,
                  "heatindex_f": 63.3,
                  "dewpoint_c": 9.2,
                  "dewpoint_f": 48.6,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 14.1,
                  "gust_kph": 22.7,
                  "uv": 1
                },
                {
                  "time_epoch": 1678842000,
                  "time": "2023-03-14 21:00",
                  "temp_c": 16.8,
                  "temp_f": 62.2,
                  "is_day": 0,
                  "condition": {
                    "text": "Cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                    "code": 1006
                  },
                  "wind_mph": 7.4,
                  "wind_kph": 11.9,
                  "wind_degree": 18,
                  "wind_dir": "NNE",
                  "pressure_mb": 1020,
                  "pressure_in": 30.12,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 62,
                  "cloud": 64,
                  "feelslike_c": 16.8,
                  "feelslike_f": 62.2,
                  "windchill_c": 16.8,
                  "windchill_f": 62.2,
                  "heatindex_c": 16.8,
                  "heatindex_f": 62.2,
                  "dewpoint_c": 9.5,
                  "dewpoint_f": 49.1,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 12.1,
                  "gust_kph": 19.4,
                  "uv": 1
                },
                {
                  "time_epoch": 1678845600,
                  "time": "2023-03-14 22:00",
                  "temp_c": 16.6,
                  "temp_f": 61.9,
                  "is_day": 0,
                  "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                  },
                  "wind_mph": 6.3,
                  "wind_kph": 10.1,
                  "wind_degree": 5,
                  "wind_dir": "N",
                  "pressure_mb": 1020,
                  "pressure_in": 30.12,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 64,
                  "cloud": 15,
                  "feelslike_c": 16.6,
                  "feelslike_f": 61.9,
                  "windchill_c": 16.6,
                  "windchill_f": 61.9,
                  "heatindex_c": 16.6,
                  "heatindex_f": 61.9,
                  "dewpoint_c": 9.9,
                  "dewpoint_f": 49.8,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 10.7,
                  "gust_kph": 17.3,
                  "uv": 1
                },
                {
                  "time_epoch": 1678849200,
                  "time": "2023-03-14 23:00",
                  "temp_c": 16.4,
                  "temp_f": 61.5,
                  "is_day": 0,
                  "condition": {
                    "text": "Cloudy",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                    "code": 1006
                  },
                  "wind_mph": 7.2,
                  "wind_kph": 11.5,
                  "wind_degree": 359,
                  "wind_dir": "N",
                  "pressure_mb": 1020,
                  "pressure_in": 30.13,
                  "precip_mm": 0,
                  "precip_in": 0,
                  "humidity": 66,
                  "cloud": 73,
                  "feelslike_c": 16.4,
                  "feelslike_f": 61.5,
                  "windchill_c": 16.4,
                  "windchill_f": 61.5,
                  "heatindex_c": 16.4,
                  "heatindex_f": 61.5,
                  "dewpoint_c": 10,
                  "dewpoint_f": 50,
                  "will_it_rain": 0,
                  "chance_of_rain": 0,
                  "will_it_snow": 0,
                  "chance_of_snow": 0,
                  "vis_km": 10,
                  "vis_miles": 6,
                  "gust_mph": 12.3,
                  "gust_kph": 19.8,
                  "uv": 1
                }
              ]
            }
          ]
        }
      }
    const [weather, setWeather] = useState()
    const inputRef = useRef(null);
    function fetchdata(){        
        axios.get('/https://group-3-backend.onrender.com?zip='+ inputRef.current.value)
            .then(function (response) {
                setWeather(response.data)
            }).catch(function (error) {
                setWeather(mockData)
                console.log(error);
            })
    }
    return(            
        <header className="App-header">  
          <div class="d-flex justify-content-center">              
              <label for="city">City / State: </label>
              <input ref={inputRef} type="text" id="city" name="city" placeholder="Example: 31907"></input>
              <Button onClick={fetchdata} variant="success">Submit</Button>{' '}
          </div>
          <br />
          <Card weatherData={weather}/>
        </header>
    )
}

export default Header